"""initial_schema

Revision ID: 7825fb7598a6
Revises: 
Create Date: 2026-07-21 07:54:37.669179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7825fb7598a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('engineer_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engineer_code'),
    sa.UniqueConstraint('username')
    )
    op.create_table('locker_stations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locker_slots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('slot_code', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='locker_size'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'OCCUPIED', 'MAINTENANCE', name='locker_status'), server_default='AVAILABLE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['locker_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'slot_code', name='uq_station_slot_code')
    )
    op.create_table('allocations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('package_identifier', sa.String(length=100), nullable=False),
    sa.Column('package_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='locker_size'), nullable=False),
    sa.Column('allocation_type', sa.Enum('COURIER', 'P2P', name='allocation_type'), server_default='COURIER', nullable=False),
    sa.Column('courier_name', sa.String(length=100), nullable=True),
    sa.Column('courier_code', sa.String(length=50), nullable=True),
    sa.Column('storer_name', sa.String(length=100), nullable=True),
    sa.Column('storer_phone', sa.String(length=50), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('recipient_phone', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('pickup_code_hash', sa.String(length=255), nullable=True),
    sa.Column('stored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_payment_paid', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_charge_applied', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['locker_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations')
    op.drop_table('locker_slots')
    op.drop_table('locker_stations')
    op.drop_table('engineers')
    # ### end Alembic commands ###
